<?php

/**
 * translator:昌维 <867597730@qq.com>
 * repository:https://github.com/cw1997/laravel-Simplified-Chinese
 * Translated as 2016-11-11 01:41:20
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    | 额外的编译类
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    | 这里也许有一些需要通过`artisan optimize`命令来构建便以稳健的扩展类需要被引入。
    | 这些类应该是几乎每次请求都会被引入的类。
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    | 文件编译提供者
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    | 在这里你可以列举一些被声明为“compiles”函数，
    | 这个函数应当返回被编译之后的扩展文件，
    | 提供一个简单的方式从任何你使用到的包中获取到公共文件。
    |
    */

    'providers' => [
        //
    ],

];
